### ISSUE TITLE
AbstractMethodError and ByteBufs

### ISSUE THREAD

**Issue by PseudoDistant** [LegacyRewoven/rewoven-api#21]
Receiver class net.minecraft.util.PacketByteBuf does not define or inherit an implementation of the resolved method 'abstract int capacity()' of abstract class io.netty.buffer.ByteBuf.

I am big sadd.

**Comment by PseudoDistant** [comment]
![capacityyyyyyyyyyyyyy](https://user-images.githubusercontent.com/67613281/147900662-9b838ce3-509b-4a97-b860-cd50b12a732b.png)
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by thecatcore** [comment]
Fixed
